[package]
name = "octopt"
version = "0.0.0"
edition = "2018"
license = "MIT"
description = "CHIP-8/Octo configuration options"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
